### ISSUE TITLE
[feature] フォーム・データ配置

### ISSUE THREAD

**Issue by mrgishi** [gohandao/ai-traveler#3]
【変更箇所】
- [x] 予算：number
- [x] 場所：プルダウン（国、都市 json）
- [x] 人数：プルダウン/number
- [x] 日数：プルダウン/number
- [x] 目的：プルダウン（後日）
- [x] RHF実装
- [x] バリデーション
- [x] エラー処理

【その他】
関連：[[feature] OpenAI APIレスポンス実装 #2](https://github.com/gohandao/ai-traveler/issues/2)

**Comment by katayama8000** [comment]
zod試してみる
